version: "3.8"
services:
  app:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:h2:tcp://db:8082/mem:test
  db:
    image: oscarfonts/h2:latest
    ports:
      - "8082:8082"
    environment:
      H2_OPTIONS: -ifNotExists